/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JMenuItem;
import javax.swing.MenuElement;
import javax.swing.MenuSelectionManager;
/**
 *
 * @author guille
 */
public class superpifli extends javax.swing.JFrame {

    /**
     * Creates new form superpifli
     */
    public superpifli() {
        initComponents();
    }
   
    int premas ;
    int preingr; 
    float Desc;
    String Entr;
    String Pers;
     

    int Masa[]={4,5,6,6,7,7,8,9};
    int Ingredientes[]={2,1,3,2,1,1,1,3,4,2,1};
    float Desconto[]={1f,0.1f,0.2f,0.25f};
    
     /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem6 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem9 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem10 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem11 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem15 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem23 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem7 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem8 = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem16 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem17 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem18 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem19 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem20 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem21 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem22 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem24 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem25 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem26 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem27 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem28 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem29 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem30 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem31 = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItem32 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem33 = new javax.swing.JCheckBoxMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jCheckBoxMenuItem34 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem35 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem36 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem37 = new javax.swing.JCheckBoxMenuItem();
        jMenu6 = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem6.setSelected(true);
        jCheckBoxMenuItem6.setText("jCheckBoxMenuItem6");

        jCheckBoxMenuItem9.setSelected(true);
        jCheckBoxMenuItem9.setText("jCheckBoxMenuItem9");

        jCheckBoxMenuItem10.setSelected(true);
        jCheckBoxMenuItem10.setText("jCheckBoxMenuItem10");

        jCheckBoxMenuItem11.setSelected(true);
        jCheckBoxMenuItem11.setText("jCheckBoxMenuItem11");

        jCheckBoxMenuItem15.setSelected(true);
        jCheckBoxMenuItem15.setText("jCheckBoxMenuItem15");

        jCheckBoxMenuItem23.setSelected(true);
        jCheckBoxMenuItem23.setText("jCheckBoxMenuItem23");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pedido");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton1.setText("Xerar Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Masa   ");
        buttonGroup1.add(jMenu1);

        buttonGroup1.add(jRadioButtonMenuItem1);
        jRadioButtonMenuItem1.setText("hiperextramega");
        jMenu1.add(jRadioButtonMenuItem1);

        buttonGroup1.add(jRadioButtonMenuItem2);
        jRadioButtonMenuItem2.setText("hipermega");
        jMenu1.add(jRadioButtonMenuItem2);

        buttonGroup1.add(jRadioButtonMenuItem3);
        jRadioButtonMenuItem3.setText("extrahiper");
        jMenu1.add(jRadioButtonMenuItem3);

        buttonGroup1.add(jRadioButtonMenuItem4);
        jRadioButtonMenuItem4.setText("megaextra");
        jMenu1.add(jRadioButtonMenuItem4);

        buttonGroup1.add(jRadioButtonMenuItem5);
        jRadioButtonMenuItem5.setText("extrafina");
        jMenu1.add(jRadioButtonMenuItem5);

        buttonGroup1.add(jRadioButtonMenuItem6);
        jRadioButtonMenuItem6.setText("megafina");
        jMenu1.add(jRadioButtonMenuItem6);

        buttonGroup1.add(jRadioButtonMenuItem7);
        jRadioButtonMenuItem7.setText("hiperfina");
        jMenu1.add(jRadioButtonMenuItem7);

        buttonGroup1.add(jRadioButtonMenuItem8);
        jRadioButtonMenuItem8.setText("fina");
        jMenu1.add(jRadioButtonMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText(" Ingredientes  ");

        jCheckBoxMenuItem16.setText("Chorizo");
        jMenu2.add(jCheckBoxMenuItem16);

        jCheckBoxMenuItem17.setText("Jamón");
        jMenu2.add(jCheckBoxMenuItem17);

        jCheckBoxMenuItem18.setText("Queso");
        jMenu2.add(jCheckBoxMenuItem18);

        jCheckBoxMenuItem19.setText("Morcilla");
        jMenu2.add(jCheckBoxMenuItem19);

        jCheckBoxMenuItem20.setText("Champiñón");
        jMenu2.add(jCheckBoxMenuItem20);

        jCheckBoxMenuItem21.setText("Lubrigante");
        jMenu2.add(jCheckBoxMenuItem21);

        jCheckBoxMenuItem22.setText("Grelos");
        jMenu2.add(jCheckBoxMenuItem22);

        jCheckBoxMenuItem24.setText("Piña");
        jMenu2.add(jCheckBoxMenuItem24);

        jCheckBoxMenuItem25.setText("Maracuya");
        jMenu2.add(jCheckBoxMenuItem25);

        jCheckBoxMenuItem26.setText("Chistorra");
        jMenu2.add(jCheckBoxMenuItem26);

        jCheckBoxMenuItem27.setText("Polbo");
        jMenu2.add(jCheckBoxMenuItem27);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Desconto   ");

        buttonGroup2.add(jCheckBoxMenuItem28);
        jCheckBoxMenuItem28.setText("0%");
        jMenu3.add(jCheckBoxMenuItem28);

        buttonGroup2.add(jCheckBoxMenuItem29);
        jCheckBoxMenuItem29.setText("10%");
        jMenu3.add(jCheckBoxMenuItem29);

        buttonGroup2.add(jCheckBoxMenuItem30);
        jCheckBoxMenuItem30.setText("20%");
        jMenu3.add(jCheckBoxMenuItem30);

        buttonGroup2.add(jCheckBoxMenuItem31);
        jCheckBoxMenuItem31.setText("25%");
        jMenu3.add(jCheckBoxMenuItem31);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Entrega   ");

        buttonGroup3.add(jCheckBoxMenuItem32);
        jCheckBoxMenuItem32.setText("Local");
        jMenu4.add(jCheckBoxMenuItem32);

        buttonGroup3.add(jCheckBoxMenuItem33);
        jCheckBoxMenuItem33.setText("Domicilio");
        jMenu4.add(jCheckBoxMenuItem33);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Personal   ");

        buttonGroup4.add(jCheckBoxMenuItem34);
        jCheckBoxMenuItem34.setText("Soledad Bernardez");
        jMenu5.add(jCheckBoxMenuItem34);

        buttonGroup4.add(jCheckBoxMenuItem35);
        jCheckBoxMenuItem35.setText("Rosario García");
        jMenu5.add(jCheckBoxMenuItem35);

        buttonGroup4.add(jCheckBoxMenuItem36);
        jCheckBoxMenuItem36.setText("Eduardo López");
        jMenu5.add(jCheckBoxMenuItem36);

        buttonGroup4.add(jCheckBoxMenuItem37);
        jCheckBoxMenuItem37.setText("Luis González");
        jMenu5.add(jCheckBoxMenuItem37);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Client Domi");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static ClientDatos VentanaClientes;
    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed

    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        VentanaClientes.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //jMenu1.getSubElements()[1].getComponent().
        for (int i=0;i<Masa.length;i++){
                if (jMenu1.getItem(i).isSelected())
                {
                  premas = Masa[i];
                  jTextArea2.setText(jTextArea2.getText()+"\n"+jMenu1.getItem(i).getText() + " " + Float.toString(premas));
                }
            }
        for (int i=0;i<Ingredientes.length;i++){
                if (jMenu2.getItem(i).isSelected())
                {
                  preingr = Ingredientes[i];
                  jTextArea2.setText(jTextArea2.getText()+"\n"+jMenu2.getItem(i).getText() + " " + Float.toString(premas));
                }
            }
 
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        VentanaClientes= new ClientDatos();
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(superpifli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(superpifli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(superpifli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(superpifli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new superpifli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem10;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem11;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem15;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem16;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem17;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem18;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem19;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem20;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem21;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem22;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem23;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem24;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem25;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem26;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem27;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem28;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem29;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem30;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem31;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem32;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem33;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem34;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem35;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem36;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem37;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem6;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
